version: '3.8'
services:
  emp-app:
    image: emp
    depends_on:
      - emp-db
    environment:
      - MONGO_SERVER=emp-db
      - MONGO_PORT=27017
      - MONGO_DB=emp
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
    ports:
      - 8080:8080
  emp-db:
    image: mongo:6.0.5-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb:/data/db/
volumes:
  mongodb:
    external: true
